platform :ios, '15.0'

target 'Vibree' do
  use_frameworks!
  pod 'LibTorch-Lite', '1.13.0.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
    if target.name == 'LibTorch-Lite' || target.name == 'Pods-Vibree'
      target.build_configurations.each do |config|
        config.build_settings['ARCHS'] = 'arm64'
        config.build_settings['VALID_ARCHS'] = 'arm64'
      end
    end
  end
end
