name: Vibree
options:
  bundleIdPrefix: com.example
targets:
  Vibree:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources: 
      - path: Vibree
    info:
      path: Info.plist
      properties:
        CFBundleVersion: 1
        CFBundleShortVersionString: 1.0
    settings:
      base:
        SWIFT_VERSION: 5
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++17"
        CLANG_CXX_LIBRARY: "libc++"
        ONLY_ACTIVE_ARCH: NO
        ARCHS: "arm64"
        VALID_ARCHS: "arm64"
        SWIFT_OBJC_BRIDGING_HEADER: Vibree/Vibree-Bridging-Header.h
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        OTHER_LDFLAGS: 
          - $(inherited)
        OTHER_CFLAGS:
          - $(inherited)
        OTHER_CPLUSPLUSFLAGS:
          - $(inherited)
        OTHER_SWIFT_FLAGS:
          - $(inherited)
        GCC_PREPROCESSOR_DEFINITIONS: 
          - $(inherited)
schemes:
  Vibree:
    build:
      targets:
        Vibree: [all]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - Vibree
