name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.5'

    - name: Download ML Models from Google Drive
      run: |
        pip install gdown
        mkdir -p android/app/src/main/assets
        gdown "1Gbtipohnlm3MUqr6q3A2-9XPqSmF1b4r" -O android/app/src/main/assets/hrv_model.ptl
        gdown "1Pm1AHtSkY5lyx4KEvIvpPl3jCCN3mcXS" -O android/app/src/main/assets/nlp_model.ptl
        gdown "1dQVTk5MRrYivX5QLv-nCj46UFRIn9qtT" -O android/app/src/main/assets/vocab.txt
        ls -lh android/app/src/main/assets/

    - name: Generate Gradle Wrapper
      working-directory: ./android
      run: gradle wrapper --gradle-version 8.5

    - name: Build with Gradle
      working-directory: ./android
      run: ./gradlew :app:assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
